# Generated by Django 2.1rc1 on 2018-08-01 16:11

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organizer", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="A label for URL config.",
                max_length=31,
                populate_from=["name"],
            ),
        )
    ]
